#! /bin/bash
export ODL_VERSION=$(cat build-args/ODL_VERSION)

cat <<ENDOFCAT
################
Build setup:

ODL_VERSION: ${ODL_VERSION}
################
ENDOFCAT

docker build --build-arg ODL_VERSION -f $DOCKERFILE_PATH -t $IMAGE_NAME .
