#! /bin/bash
export ODL_VERSION=$(cat build-args/ODL_VERSION)

cat <<ENDOFCAT
################
Test setup:

ODL_VERSION: ${ODL_VERSION}
################
ENDOFCAT

if echo "feature:list" | docker run -e KARAF_INTERACTIVE=1 -i $IMAGE_NAME . | grep -i "karaf shell"; then
    echo "OK:    karaf shell was found in output of feature:list"
else
    echo "FATAL: karaf shell was not found in output of feature:list"
    exit 100
fi
